from emotiment.constant.config_constant import TRAINING_CONFIG_PATH
from emotiment.constant.training_constant import GRID_MODE, MONO_MODE, EMOJI2VEC_METHOD, EMOJI2DESCRIPTION_METHOD
from emotiment.constant.model_constant import MODEL_LIST